
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Nov 10 2025 18:02:18 EST (Nov 10 2025 23:02:18 UTC)

// Verification Directory fv/mux4to1 

module mux4to1(a, b, c, d, sel, out);
  input [3:0] a, b, c, d;
  input [1:0] sel;
  output [3:0] out;
  wire [3:0] a, b, c, d;
  wire [1:0] sel;
  wire [3:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  ND2D1BWP16P90 g358__2398(.A1 (n_2), .A2 (n_6), .ZN (out[3]));
  ND2D1BWP16P90 g359__5107(.A1 (n_11), .A2 (n_7), .ZN (out[2]));
  ND2D1BWP16P90 g361__6260(.A1 (n_10), .A2 (n_0), .ZN (out[1]));
  ND2D1BWP16P90 g360__4319(.A1 (n_1), .A2 (n_3), .ZN (out[0]));
  AOI22D1BWP16P90LVT g366__8428(.A1 (n_9), .A2 (a[2]), .B1 (n_8), .B2
       (b[2]), .ZN (n_11));
  AOI22D1BWP16P90LVT g363__5526(.A1 (n_9), .A2 (a[1]), .B1 (n_8), .B2
       (b[1]), .ZN (n_10));
  AOI22D1BWP16P90LVT g362__6783(.A1 (n_5), .A2 (c[2]), .B1 (n_4), .B2
       (d[2]), .ZN (n_7));
  AOI22D1BWP16P90LVT g364__3680(.A1 (n_5), .A2 (c[3]), .B1 (n_4), .B2
       (d[3]), .ZN (n_6));
  AOI22D1BWP16P90LVT g368__1617(.A1 (n_5), .A2 (c[0]), .B1 (n_4), .B2
       (d[0]), .ZN (n_3));
  AOI22D1BWP16P90LVT g365__2802(.A1 (n_9), .A2 (a[3]), .B1 (n_8), .B2
       (b[3]), .ZN (n_2));
  AOI22D1BWP16P90LVT g367__1705(.A1 (n_9), .A2 (a[0]), .B1 (n_8), .B2
       (b[0]), .ZN (n_1));
  AOI22D1BWP16P90LVT g369__5122(.A1 (n_5), .A2 (c[1]), .B1 (n_4), .B2
       (d[1]), .ZN (n_0));
  NR2D1BWP16P90 g370__8246(.A1 (sel[1]), .A2 (sel[0]), .ZN (n_9));
  INR2D1BWP16P90 g371__7098(.A1 (sel[1]), .B1 (sel[0]), .ZN (n_5));
  AN2D1BWP16P90 g372__6131(.A1 (sel[1]), .A2 (sel[0]), .Z (n_4));
  INR2D1BWP16P90 g373__1881(.A1 (sel[0]), .B1 (sel[1]), .ZN (n_8));
endmodule

