
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Nov 16 2025 18:32:44 EST (Nov 16 2025 23:32:44 UTC)

// Verification Directory fv/mux4to1 

module mux4to1(a, b, c, d, sel, clk, resetn, out);
  input [3:0] a, b, c, d;
  input [1:0] sel;
  input clk, resetn;
  output [3:0] out;
  wire [3:0] a, b, c, d;
  wire [1:0] sel;
  wire clk, resetn;
  wire [3:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17;
  DFQD2BWP16P90LVT \out_reg[3] (.CP (clk), .D (n_14), .Q (out[3]));
  DFQD2BWP16P90LVT \out_reg[2] (.CP (clk), .D (n_15), .Q (out[2]));
  DFQD2BWP16P90LVT \out_reg[0] (.CP (clk), .D (n_16), .Q (out[0]));
  DFQD2BWP16P90LVT \out_reg[1] (.CP (clk), .D (n_17), .Q (out[1]));
  ND2D1BWP16P90LVT g413__2398(.A1 (n_3), .A2 (n_12), .ZN (n_17));
  ND2D1BWP16P90LVT g415__5107(.A1 (n_2), .A2 (n_4), .ZN (n_16));
  ND2D1BWP16P90LVT g414__6260(.A1 (n_13), .A2 (n_6), .ZN (n_15));
  ND2D1BWP16P90LVT g416__4319(.A1 (n_8), .A2 (n_10), .ZN (n_14));
  AOI22D1BWP16P90LVT g420__8428(.A1 (n_7), .A2 (c[2]), .B1 (n_11), .B2
       (d[2]), .ZN (n_13));
  AOI22D1BWP16P90LVT g417__5526(.A1 (n_9), .A2 (b[1]), .B1 (n_11), .B2
       (d[1]), .ZN (n_12));
  AOI22D1BWP16P90LVT g424__6783(.A1 (n_5), .A2 (a[3]), .B1 (n_9), .B2
       (b[3]), .ZN (n_10));
  AOI22D1BWP16P90LVT g421__3680(.A1 (n_7), .A2 (c[3]), .B1 (n_11), .B2
       (d[3]), .ZN (n_8));
  AOI22D1BWP16P90LVT g423__1617(.A1 (n_5), .A2 (a[2]), .B1 (n_9), .B2
       (b[2]), .ZN (n_6));
  AOI22D1BWP16P90LVT g422__2802(.A1 (n_9), .A2 (b[0]), .B1 (n_11), .B2
       (d[0]), .ZN (n_4));
  AOI22D1BWP16P90LVT g418__1705(.A1 (n_5), .A2 (a[1]), .B1 (n_7), .B2
       (c[1]), .ZN (n_3));
  AOI22D1BWP16P90LVT g419__5122(.A1 (n_5), .A2 (a[0]), .B1 (n_7), .B2
       (c[0]), .ZN (n_2));
  NR2D1BWP16P90LVT g425__8246(.A1 (n_1), .A2 (sel[0]), .ZN (n_7));
  INR2D1BWP16P90LVT g426__7098(.A1 (n_0), .B1 (sel[0]), .ZN (n_5));
  INR2D1BWP16P90LVT g428__6131(.A1 (sel[0]), .B1 (n_1), .ZN (n_11));
  AN2D1BWP16P90LVT g427__1881(.A1 (n_0), .A2 (sel[0]), .Z (n_9));
  NR2D1BWP16P90LVT g429__5115(.A1 (resetn), .A2 (sel[1]), .ZN (n_0));
  IND2D1BWP16P90LVT g430__7482(.A1 (resetn), .B1 (sel[1]), .ZN (n_1));
endmodule

